apiVersion: v1
kind: ConfigMap
metadata:
  name: product-catalog-config
data:
  PRODUCT_CATALOG_PORT: "8088"
  FLAGD_HOST: "flagd"
  FLAGD_PORT: "8013"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring.svc.cluster.local:4317"