apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog
  labels:
    app: product-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog
  template:
    metadata:
      labels:
        app: product-catalog
    spec:
      serviceAccountName: product-catalog-sa
      containers:
      - name: product-catalog
        image: basabesso/product-catalog:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
        envFrom:
        - configMapRef:
            name: product-catalog-config
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "100m"
        livenessProbe:
          grpc:
            port: 8088
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          grpc:
            port: 8088
          initialDelaySeconds: 5
          periodSeconds: 5
