apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-detection-config
data:
  KAFKA_SERVICE_ADDR: "kafka:9092"
  KAFKA_ADDR: "kafka:9092"
  FLAGD_HOST: "flagd"
  FLAGD_PORT: "8013"
  OTEL_SERVICE_NAME: "fraud-detection"
  OTEL_SDK_DISABLED: "true"
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "cumulative"
  OTEL_INSTRUMENTATION_KAFKA_EXPERIMENTAL_SPAN_ATTRIBUTES: "true"
  OTEL_INSTRUMENTATION_MESSAGING_EXPERIMENTAL_RECEIVE_TELEMETRY_ENABLED: "true"
  OTEL_RESOURCE_ATTRIBUTES: "service.namespace=opentelemetry-demo"