apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-detection-config
data:
  KAFKA_SERVICE_ADDR: "kafka:9092"
  OTEL_SERVICE_NAME: "fraud-detection"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost:4317"
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "cumulative"
  OTEL_RESOURCE_ATTRIBUTES: "service.namespace=opentelemetry-demo"