apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagd
  labels:
    app: flagd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flagd
  template:
    metadata:
      labels:
        app: flagd
    spec:
      containers:
        - name: flagd
          image: ghcr.io/open-feature/flagd:v0.14.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8013
            - containerPort: 8016
          args:
            - start
            - --uri
            - file:/etc/flagd/demo.flagd.json
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi