apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-quota
  namespace: prod
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: ecommerce
    environment: prod
spec:
  hard:
    requests.cpu: "12000m"
    limits.cpu: "24000m"

    requests.memory: "12Gi"
    limits.memory: "24Gi"

    pods: "120"
    services: "40"
    persistentvolumeclaims: "10"
    secrets: "20"
    configmaps: "40"