apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
data:
  PAYMENT_PORT: "50051"
  OTEL_SERVICE_NAME: "payment"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost:4317"
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "cumulative"
  OTEL_RESOURCE_ATTRIBUTES: "service.namespace=dev"