apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: basabesso/paymentservice:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          envFrom:
            - configMapRef:
                name: payment-config
            - secretRef:
                name: payment-secret
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi