---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-secret
  namespace: dev
spec:
  encryptedData:
    STRIPE_TOKEN: AgCJ/PAVxOQTngAjOpjjgPyFoaIfz3JiA7BN81GX0ThDxfdrGhj9zuM1gnRILSUrX1koWxdNjGKJf33WJCZ01bRROFXrPIHfbvSPPzuP4pybd8zrYNSZmotHBu3d8GNP3Y7VWi4g3aPEShf/9xHyMk/fkOWTHeiK4BE+yMX5AKmV/VOKSxQoagSJpoKMj2nLb/05kpfkeAeAlMLDXB29abt6NYY469Q4Jkerg+xwrlU99ecQlByU0pUogML4MW4gu246b+XoheSNqTmQJz3MPX7/+Ple/kX97cJxW0LfsOleaKfB0N7fGuHV/lmGScXbTXUn4ChOV/O0zvlWc9EVEze6zsB0IwYpQ6KnPx2Dvoh7MFRT4k7EfTN/Olq8qYOuJ5nz8GsqszQthvTVDLYsHV2UbSQGowjzdKraaf0nEMljXKoTt7IOCHZGjp4lFfSjLFmm+Ivy7Y7rocAzJ2G+2Fm2R/lUd3rjHy2lhbLm/Lqwpf6aeJDb3gLV9valkNJomm5rTWZjV8UMH+JLO0/NctoUEZjqLzjL5bLnru55li60m2v/rIQPDjpigZVs7ECm/nehkb8pvZhqMyt2ImJ0sYDf3BbyAJf9iL1RTMwVx98CrQ1qYOwmlsj/L6dtV7KACDFpsD8wgy04RYl4uGyhph+1J92Xe9gFIA3/onYP+EHvDOtx132N+4fmhwXVR0Yud213l77V8bTX6voKZmFTTo/6xg==
  template:
    metadata:
      creationTimestamp: null
      name: payment-secret
      namespace: dev
    type: Opaque
