---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: payment-secret
spec:
  encryptedData:
    STRIPE_TOKEN: AgAVjpEcEUu6actlVx3q7xNMIlTnWDGC26E8glc9ou1gIoaZ6kNymZSec2s0sLr+p7F9adkE6tOmfBubzxW25gItme+HkLdQyxkk2vDj2DSusqwTo8BiFkMAtEGfRVVRf3pYop+vAecJ+XtkAY3mp4Ve/GdNNTQpf7ML6nMf8/de03lB0reROdddte3eW/GHnu7P94/q0AXZs8qGbQehXciMaR/9FbyXUo9hi8HzX1FyUJKz6X3iuZbqEa1kQRonhTzLLtF4dFolFJLR32h+fNvi8tsz2X3lI51tmA1f2D0jfI7mALK9mW0FISoBbuv/WVJaS3JGwtf1GiME07zu/PlQG45JBtb5gAuXpPUkLVi4dKhfETLs6P4wBP1hKnMU9SWCjGFIdMcLZP2unRCb3WDRYRerfFSp5XlFQOKgAJcj0hI//XV0bMn03i1Q0faKxkxw56jNTF90XEmpufns/ru4OKK8bEDGimD+bMsg4K+I2VpJ7vVIhDfYjetp6J7H5QQUkDGc0+XiY09eC5YL+ok2L/72pO1RLad82MzUEzCYzW+U/6N19YMDX9y++9veZi9Y70UBvVh3iSl6o5RshhVEEpYH++HoLgnb1q9JIDJUFd7ae7CVW2/56jY/FMJkaj0vWLyKgvZLuPGUkmSnHpfDQoiN8eafB2sjTjzPSWYolNpNYJDgySec09UuyCffaFP5/y6XyVzPuvlHVe+gaD/a4A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: payment-secret
    type: Opaque
