apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad-service
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: ad-service
          resources:
            requests:
              cpu: 150m
              memory: 300Mi
            limits:
              cpu: 300m
              memory: 600Mi