apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: cart
          image: 707938860152.dkr.ecr.eu-north-1.amazonaws.com/ecommerce-prod/cart:c58583b
          resources:
            requests:
              cpu: 150m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi