apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagd-ui
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: flagd-ui
          resources:
            requests:
              cpu: 150m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi