apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: payment
          image: 707938860152.dkr.ecr.eu-north-1.amazonaws.com/ecommerce-prod/payment:78e59c4
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi