apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-reviews
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: product-reviews
          resources:
            requests:
              cpu: 400m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi