apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: ghcr.io/open-telemetry/demo:latest-cartservice
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
          envFrom:
            - configMapRef:
                name: cart-config
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi