apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
  KAFKA_KRAFT_MODE: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost:4317"
  OTEL_SERVICE_NAME: "kafka"
  KAFKA_HEAP_OPTS: "-Xmx400m -Xms400m"