apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: ghcr.io/open-telemetry/demo:1.12.0-kafka
          imagePullPolicy: Always
          ports:
            - containerPort: 9092
            - containerPort: 9093
          envFrom:
            - configMapRef:
                name: kafka-config
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
          resources:
            requests:
              cpu: 200m
              memory: 400Mi
            limits:
              cpu: 500m
              memory: 600Mi
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-pvc