---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: accounting-secret
spec:
  encryptedData:
    POSTGRES_ADDR: AgCVfMoEmdhmDA+hXMlRxaD9ZNDSns9H/k317lfl5NJf4KpqzygIyBCfrVZsEE1iZLM6ITIVXYDV/h4ZrYj7KPcztdKkZ8U0ZumNTAgi7Pn6Nr+t+qNTEpNUoLsptjVrTr7sE9sK8FDRTz0GAuzmPzDJ36KK5Ntai6PlkOba2z2ZMCX3gK+auxKZLx4F5Y8vovphnraWkmsxMOBSYonEBHAtO9+hl6ELciNy3Xh4GzyHXGpztwIt6z7jbt1ZqrSNxua840dGifZWzA019eO5zuDR4IZrA80DOVDO3xi1xAQHkK6gkguWM0NJT1tHFDHvpaJV45jKsA78CAPaVl5tKkJ0wIQplNkYshs/vdww1MuKnbxJKBA32lM6/3oObiV3G2WT5PHq/gGycwT2ym9sEmBmtzTdX/kzaF4/yZQwLo/UqApkJ6qZleJfu2oZ/baU0VNud3s74JPtrID+36y/mGpzAx4tzIik+6OGp0YmSqJ0GIAmpfvCKbP/BxV59Hk9pmweWY0tNeK+5Lav5VZcnLC5a7f3pK6wWSPMCZm/yLFhjm/QXoe84d17YWVEP8CMzIZJ7z66btBs7G8VJWvoOJlCnVn1tr/fBsy9vGgxooJetkxIK7Gh2A8nLIShn1TpoMMorYpfndNgwHqIS/UL19M7Ho1HnJHbFa5Z+Lp8LmuMoQZgiaha3QIiBFVvRrmrlOvuj6PQ8ODP+2gUCo1MeII=
    POSTGRES_PASSWORD: AgB9Qkyeq6lwddZSzBdtQWrzaAtg1UW5A8ERUvCVDPjekECqLtiTxeor1E/hgBbm/FhCaRqjKb5D2Ass/GgLj8DzxPam3Gu4H+M25N2S/XKwCRmlDf/RzXtG9eqfPqdEXLaWKtdUUokntUQ7tJWwYYv0kKeeXzv79KBFmgW7rMmuThCjeIIz63840AtspEMbuf2GFKaNDyx8tjq4r6aYr+x3qvvwVT06Dc0jZDLB0o33XNP5pbIXtowUVCA5ME3d/l8Yziucu982l3bfzc/sq+cQVRgr+GAGFr9oTLwTq3t05Xo2HpK+j62YUyIa0KUG8M+VKIhY7a32FxpkU6mIHhk34miZJZZXtt06qIeCIF6OrKFCdwdS5dUbtm4MG+jLobk0GQMeK4Y5KfLNPFE7e4zvNejc335iLYnuP/EBnXnWjXD8wk3TcJvyNmac3FErtp7Wvl9IZkDuDwFyt4d2ZPtH7k1JZAexIwH53iMIbIIbIvArmwq8rokFafEBNIuFDbT2vMM/7LVAFaRfgYR93wAEwmo5QgcOI9F09OO23Jd8h91Jc23YSYzmWjaveHIE/B75XdWfkeon2GzZZ81RlXfY5D7PJ2cjpspOIyVo+5YT0R+hZjVty9iTLpy+xq3cv6VatzeA0G7a02ljxt4C99QSTru3Mj4rGfLpZbpZKfFrt+laDbh0VnNtXLHSMnF2iVnSXSUA
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: accounting-secret
    type: Opaque
