---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: accounting-secret
  namespace: dev
spec:
  encryptedData:
    POSTGRES_ADDR: AgDGpZ4GeUgll4E53qSXqpdYjmvFJfqcgILalDOf8MI+rmbBxdZkcChLryDVaGCO1pJ14S2h7NT34yp+J6wT6EV3SHdJwelIa8U0hvtfPJS9GKnG9nrjn1+cbxdsFw64GsCujdV43eUt+VSM2O5n+kCfVRTGlmWsX/1ZRwLnHklbVLieFezBR+JPTZIu6CFevMTgxK08DBnL7EwR2FF89lPhSE9f+d/UnWHvPlAR/157ZSMepDRqn76MH5uo0XqZ2jmLWefurQUFzXWTMmdWKpjVgguapm/FIX014e47a+eOsL+vA8eBhGz7QBGYVNOwUKiIfDlAWiX1xhpXFrWLmgjBkal5Ka0SYvZj7y7K47hFpDDzGc1uDRi6L7I9AYZkIYm/3lOkFNbSrHg8b+3BU3Sfrs/9lqMx2j/2mlWShPRQUFEick8XLSSbcMzExjeZKrKV+ftUvu+fC4atT1UE/Bp5NcrR4CWVce1ooekpNfLULvzLJbtt4f2E9I4JbPI4SCMla75B7xEetBCFklI3/mXkz1OqeOrnY7hDZhdc9rK6j2lsCO2VhBkzpFxS1yoK/LE2VJ5ZNO8k3t8HTbjtHrGlwxfo+mY2Z1VUR33V5i/UlgE0Q4EmXxfcQlfZrJGzOzqG+ytnq6oQclJ3UMn72eKHh1rRuR94MlcmidrKq+CFb8p2MoPz31uOaoxGsp7Xk21SXEsMRs3XEesY3ZDOj/o=
    POSTGRES_PASSWORD: AgCe/uUQkxI1qz/9eXbG1us7JyAxS7We7D8n67F+1OwN61AhJlFOnxAAeuXcBoVkJ1p+JwtCFHbY4SYL4Lb7YO3pKdViI0mqn+3hbuMDUfBHBP2kGXk0/4YJUcvgNx267cg9alA/Be2W4kqcRZh0krfUQTmLr4638Li5Elg2NahEQQtWaZrCWlk9yfnmgjK1DnNqOIooX2OK9CXuDh6sdUPZGxtlLZTFkka4T6VE68ct/rl84Nq0yA7/mKfA0WF5CuW2jZ5APVq4fzIbVzN4jvts3cFog89Hnjtb2otv+5aV/V+0LtRhw+xrMOPbgBuTiqws6knqB9T8I+q5/y+dpcFB3mnAJPgbZLjbnopA8orE99MZtzn86UtaM2MJR5UBpGUnYIszDCpzd4N3plDQELelBcnOlBFyPZtXFa92FglzNdtnRkwoUBklEeU3J0Sct+LS1+2XeDbNQRg3aGTYpI43cmowfYET6UauTlirMAffmnCrhQ0D0mvNryFnt2QIyTVKEljBR9P58vN9lvki6L19BKSvL5g5ZEKUW+SbHpCa64aa948kpjwsexo+7ImT6S3LqKSYmBpBXU2lCfawOy++SdoELNJfNaML2lKvTtQeE+RsZIbF9daNupqaqXJLerbWUg9u4H29QCnB977Y5eOqZm9FEF5PxYoZDi8jnIMtfGwD+SEgzP5X7CPInuLBMuMskWd0
  template:
    metadata:
      creationTimestamp: null
      name: accounting-secret
      namespace: dev
    type: Opaque
