apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  FRONTEND_PORT: "8080"
  PORT: "8080"
  FRONTEND_ADDR: ":8080"
  AD_SERVICE_ADDR: "ad-service:9099"
  AD_ADDR: "ad-service:9099"
  CART_SERVICE_ADDR: "cart:8080"
  CART_ADDR: "cart:8080"
  CHECKOUT_SERVICE_ADDR: "checkout:5050"
  CHECKOUT_ADDR: "checkout:5050"
  CURRENCY_SERVICE_ADDR: "currency:7001"
  CURRENCY_ADDR: "currency:7001"
  PRODUCT_CATALOG_SERVICE_ADDR: "product-catalog:8088"
  PRODUCT_CATALOG_ADDR: "product-catalog:8088"
  RECOMMENDATION_SERVICE_ADDR: "recommendation-service:1010"
  RECOMMENDATION_ADDR: "recommendation-service:1010"
  SHIPPING_SERVICE_ADDR: "shipping:50050"
  SHIPPING_ADDR: "shipping:50050"
  OTEL_SERVICE_NAME: "frontend"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost:4317"
  OTEL_RESOURCE_ATTRIBUTES: "service.namespace=opentelemetry-demo"
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "cumulative"
  WEB_OTEL_SERVICE_NAME: "frontend-web"
  PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://localhost:8080/otlp-http/v1/traces"
  OTEL_COLLECTOR_HOST: "otel-collector"
  ENV_PLATFORM: "local"
  FLAGD_HOST: "flagd"
  FLAGD_PORT: "8013"

  PRODUCT_REVIEWS_SERVICE_ADDR: "product-reviews:3551"
  LLM_SERVICE_ADDR: "llm:8000"