apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-config
data:
  CHECKOUT_PORT: "5050"
  CART_SERVICE_ADDR: "cart:7070"
  CURRENCY_SERVICE_ADDR: "currency:7001"
  EMAIL_SERVICE_ADDR: "http://email:6060"
  PAYMENT_SERVICE_ADDR: "payment:50051"
  PRODUCT_CATALOG_SERVICE_ADDR: "product-catalog:8088"
  SHIPPING_ADDR: "shipping:50050" 
  FLAGD_HOST: "flagd"
  FLAGD_PORT: "8013"
  OTEL_SERVICE_NAME: "checkout"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost:4317"
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "cumulative"
  OTEL_RESOURCE_ATTRIBUTES: "service.namespace=opentelemetry-demo"