apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad-service
  labels:
    app: ad-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad-service
  template:
    metadata:
      labels:
        app: ad-service
    spec:
      containers:
        - name: ad-service
          image: basabesso/adservice:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 9099
          envFrom:
            - configMapRef:
                name: ad-service-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi