apiVersion: v1
kind: ConfigMap
metadata:
  name: product-reviews-config
data:
  PRODUCT_REVIEWS_PORT: "3551"
  OTEL_SERVICE_NAME: "product-reviews"
  DB_CONNECTION_STRING: "host=postgresql user=otel password=otel dbname=otel"
  LLM_HOST: "llm"
  LLM_PORT: "8000"
  LLM_BASE_URL: "http://llm:8000/v1"
  OPENAI_API_KEY: "dummy"
  LLM_MODEL: "astronomy-llm"
  PRODUCT_CATALOG_ADDR: "product-catalog:8088"
  FLAGD_HOST: "flagd"
  FLAGD_PORT: "8013"
  OTEL_PYTHON_LOG_CORRELATION: "true"
  OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT: "true"
  PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: "python"
  # OTEL_SDK_DISABLED: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring.svc.cluster.local:4317"
  # OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "cumulative"
  # OTEL_RESOURCE_ATTRIBUTES: "service.namespace=opentelemetry-demo"