apiVersion: v1
kind: ConfigMap
metadata:
  name: product-reviews-config
data:
  PRODUCT_REVIEWS_PORT: "3551"
  OTEL_SERVICE_NAME: "product-reviews"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost:4317"
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "cumulative"
  OTEL_RESOURCE_ATTRIBUTES: "service.namespace=opentelemetry-demo"