apiVersion: v1
kind: ConfigMap
metadata:
  name: currency-config
data:
  CURRENCY_PORT: "7001"
  OTEL_SERVICE_NAME: "currency"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost:4317"
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "cumulative"
  OTEL_RESOURCE_ATTRIBUTES: "service.namespace=opentelemetry-demo"
  VERSION: "latest"
  IPV6_ENABLED: "false"