apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency
  labels:
    app: currency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
    spec:
      serviceAccountName: currency-sa
      containers:
        - name: currency
          image: ghcr.io/open-telemetry/demo:1.12.0-currencyservice
          imagePullPolicy: Always
          ports:
            - containerPort: 7001
          envFrom:
            - configMapRef:
                name: currency-config
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          livenessProbe:
            tcpSocket:
              port: 7001
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 7001
            initialDelaySeconds: 5
            periodSeconds: 5