apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-postgres-secret
  namespace: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: ecommerce-prod-rds-password
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: ecommerce-prod-rds-password
        property: password
    - secretKey: POSTGRES_DB
      remoteRef:
        key: ecommerce-prod-rds-password
        property: dbname
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: ecommerce-prod-rds-password
        property: host
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: ecommerce-prod-rds-password
        property: port