apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  labels:
    app: recommendation-service
spec:
  type: ClusterIP
  selector:
    app: recommendation-service
  ports:
    - port: 1010
      targetPort: 1010
      protocol: TCP