apiVersion: v1
kind: Service
metadata:
  name: ad-service
  namespace: dev
  labels:
    app: ad-service
spec:
  type: ClusterIP
  selector:
    app: ad-service
  ports:
    - port: 9099
      targetPort: 9099
      protocol: TCP