apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    app: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
        - name: shipping
          image: ghcr.io/open-telemetry/demo:latest-shippingservice
          imagePullPolicy: Always
          ports:
            - containerPort: 50050
          envFrom:
            - configMapRef:
                name: shipping-config
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi