apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote
  labels:
    app: quote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote
  template:
    metadata:
      labels:
        app: quote
    spec:
      serviceAccountName: quote-sa
      containers:
        - name: quote
          image: ghcr.io/open-telemetry/demo:latest-quoteservice
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: quote-config
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          livenessProbe:
            tcpSocket:
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8090
            initialDelaySeconds: 5
            periodSeconds: 5