apiVersion: v1
kind: ConfigMap
metadata:
  name: email-config
data:
  EMAIL_PORT: "6060"
  OTEL_SERVICE_NAME: "email"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost:4317"
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "cumulative"
  OTEL_RESOURCE_ATTRIBUTES: "service.namespace=dev"