apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-monitoring-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Besso2003/ecommerce-aws-eks-devops
    targetRevision: main
    path: k8s/overlays/monitoring/prod
  destination:
    name: prod
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
