apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Besso2003/ecommerce-aws-eks-devops.git
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    name: dev
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true