apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: cart
          image: 707938860152.dkr.ecr.eu-north-1.amazonaws.com/ecommerce-dev/cart:be4c2f0
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi