apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: checkout
          image: 707938860152.dkr.ecr.eu-north-1.amazonaws.com/ecommerce-dev/checkout:c58583b
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi