apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-provider
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: image-provider
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi