apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: payment
          image: 707938860152.dkr.ecr.eu-north-1.amazonaws.com/ecommerce-dev/payment:5850b2c
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi