apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-proxy-config
data:
  ENVOY_PORT: "8080"
  ENVOY_ADDR: "0.0.0.0"
  ENVOY_ADMIN_PORT: "10000"
  FRONTEND_HOST: "frontend"
  FRONTEND_PORT: "8080"
  FLAGD_HOST: "flagd"
  FLAGD_PORT: "8013"
  FLAGD_UI_HOST: "flagd-ui"
  FLAGD_UI_PORT: "4000"
  IMAGE_PROVIDER_HOST: "image-provider"
  IMAGE_PROVIDER_PORT: "8081"
  LOAD_GENERATOR_HOST: "load-generator"
  LOAD_GENERATOR_PORT: "8089"
  LOCUST_WEB_HOST: "load-generator"
  LOCUST_WEB_PORT: "8089"
  GRAFANA_HOST: "grafana"
  GRAFANA_PORT: "3000"
  GRAFANA_SERVICE_HOST: "grafana"
  GRAFANA_SERVICE_PORT: "3000"
  JAEGER_HOST: "jaeger"
  JAEGER_PORT: "16686"
  JAEGER_UI_PORT: "16686"
  JAEGER_SERVICE_HOST: "jaeger"
  JAEGER_SERVICE_PORT: "16686"
  OTEL_COLLECTOR_HOST: "otel-collector"
  OTEL_COLLECTOR_PORT_GRPC: "4317"
  OTEL_COLLECTOR_PORT_HTTP: "4318"
  TELEMETRY_DOCS_HOST: "telemetry-docs"
  TELEMETRY_DOCS_PORT: "8000"
  OTEL_SERVICE_NAME: "frontend-proxy"
  OTEL_RESOURCE_ATTRIBUTES: "service.namespace=opentelemetry-demo"