apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-proxy
  labels:
    app: frontend-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-proxy
  template:
    metadata:
      labels:
        app: frontend-proxy
    spec:
      containers:
        - name: frontend-proxy
          image: ghcr.io/open-telemetry/demo:latest-frontendproxy
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: frontend-proxy-config
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5