apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base/product-catalog
  - ../../base/ad-service
  - ../../base/recommendation-service
  - ../../base/currency
  - ../../base/email
  - ../../base/payment

patches:
  - path: patches/product-catalog-patch.yaml
    target:
      kind: Deployment
      name: product-catalog
  - path: patches/ad-service-patch.yaml
    target:
      kind: Deployment
      name: ad-service
  - path: patches/recommendation-service-patch.yaml
    target:
      kind: Deployment
      name: recommendation-service
  - path: patches/currency-patch.yaml
    target:
      kind: Deployment
      name: currency
  - path: patches/email-patch.yaml
    target:
      kind: Deployment
      name: email
  - path: patches/payment-patch.yaml
    target:
      kind: Deployment
      name: payment