# apiVersion: v1
# kind: ResourceQuota
# metadata:
#   name: dev-quota
#   namespace: dev
#   labels:
#     app.kubernetes.io/managed-by: kustomize
#     app.kubernetes.io/part-of: ecommerce
#     environment: dev
# spec:
#   hard:
#     requests.cpu: "3000m"
#     limits.cpu: "6000m"
    
#     requests.memory: "3Gi"
#     limits.memory: "6Gi"
    
#     pods: "60"
#     services: "40"
#     persistentvolumeclaims: "10"
#     secrets: "20"
#     configmaps: "40"