name: Terraform Plan (PR)

on:
  pull_request:
    paths:
      - "Terraform/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::707938860152:role/github-actions-terraform-plan
          aws-region: eu-north-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: Terraform/environments/dev
        run: terraform init

      - name: Terraform Plan
        working-directory: Terraform/environments/dev
        id: plan
        run: terraform plan -no-color -lock=false -var="aws_profile="
        continue-on-error: true

      - name: Comment plan on PR
        uses: actions/github-script@v7
        with:
          script: |
            const output = `#### Terraform Plan: \`dev\`
            \`\`\`
            ${{ steps.plan.outputs.stdout }}
            \`\`\`
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });