apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
  namespace: dev
  labels:
    app: recommendation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
    spec:
      containers:
        - name: recommendation-service
          image: basabesso/recommendationservice:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 1010
          env:
            - name: RECOMMENDATION_PORT
              value: "1010"
            - name: PRODUCT_CATALOG_ADDR
              value: "product-catalog:8088"
            - name: OTEL_SERVICE_NAME
              value: "recommendation-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://localhost:4317"
            - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: "cumulative"
            - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
              value: "python"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi